---
title: "R_notebook"
author: "YiChun Sung"
date: "2017年5月1日"
output: html_document
---

### 隨意筆記

## install and library multiple packages
```{r}
packages_to_use <- c("devtools", "roxygen2")
install.packages(packages_to_use)
lapply(packages_to_use, library, character.only = TRUE)

```



## 一次讀多個.csv的方法

```{r}
fileList <- list.files(path = "C://testDOC/data/", pattern="*.csv") # path = 資料夾路徑
for (i in 1:length(fileList)){
  assign(fileList[i],  # fileList[i] : data frame 命名
         read.csv(paste("C://testDOC/data/", fileList[i], sep=''))
  )}

```


## format time data

```{r}

# for example "%Y"
testTime <- c("2012-02-06 10:30:22", "2011-06-21 08:22:00", "2009-12-31 12:07:03")
subY <- format(as.Date(testTime), format="%Y")

# for example "%H"
subH <- format(as.POSIXct(testTime), format="%H")

```

## one data frame multiple polygons

use function sp::SpatialPolygons object, which works nicely with Leaflet: 

```{r}
library(dplyr)
library(sp)
library(leaflet)

dataframeToPolygons <- function(df, latCol, lngCol, idCol) {
  SpatialPolygons(lapply(unique(df[[idCol]]), function(id) {
    Polygons(list(Polygon(as.matrix(
      df[df[[idCol]] == id, c(lngCol, latCol)]
    ))), id)
  }))
}

df <- data.frame(lat = c(36.1, 36, 36, 36.1, 36.1, 36, 36), lng = c(-94.17, -94.2, -94.14, -94.2, -94.14, -94.14, -94.2), shape = c("triangle", "triangle", "triangle", "square", "square", "square", "square"))

df %>% dataframeToPolygons("lat", "lng", "shape") %>%
  leaflet() %>% addPolygons()


```